version: 2
commands:
  install-sudo:
    steps:
      - run:
          name: "Install Sudo"
          command: |
            apt-get update
            apt-get install -y sudo
  install-wget:
    steps:
      - run:
          name: "Install Wget"
          command: |
            sudo apt-get install -y wget
  install-dockerize:
    steps:
      - run:
          name: Install dockerize
          environment:
            DOCKERIZE_VERSION: v0.3.0
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
  install-mysql:
    steps:
      - run:
          name: "Install mysql client"
          command: |
            sudo apt-get -y update && sudo apt-get install -y default-mysql-client tzdata
  setup-timezone:
    steps:
      - run:
          name: Set timezone to Singapore time (arbitrary timezone to test date logic)
          command: |
            sudo apt-get install --reinstall tzdata
            sudo cp /usr/share/zoneinfo/Asia/Singapore /etc/localtime
jobs:
  build-dockerize:
    docker:
    - image: cimg/go:1.20.5
    - image: cimg/mysql:8.0
      environment:
        MYSQL_USER: circleci_test
        MYSQL_DB: circleci_test
        MYSQL_PASSWORD: circleci_test
    steps:
    - checkout
    - run: apt-get update && apt-get install wget
    - install-sudo
    - setup-timezone
    - install-dockerize
    - run:
        name: Waiting for Postgres to be ready
        command: dockerize -wait tcp://localhost:3306 -timeout 1m
    
    - run:
        name: Check DB connection
        command: |
          export MYSQL_HOST="127.0.0.1"
          export MYSQL_USER=circleci_test
          export MYSQL_PASSWORD=circleci_test
          export MYSQL_DB=circleci_test
          mysql -h 127.0.0.1 -P 3306 -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -e "show databases;"
  build-dockerize-on-remote:
    docker:
    - image: cimg/go:1.20.5
    - image: cimg/mysql:8.0
      environment:
        MYSQL_USER: circleci_test
        MYSQL_DB: circleci_test
        MYSQL_PASSWORD: circleci_test
    steps:
    - checkout
    - run: apt-get update && apt-get install wget
    - install-sudo
    - setup-timezone
    - install-dockerize
    - setup_remote_docker:
        docker_layer_caching: false
    - run:
        name: Waiting for Postgres to be ready
        command: dockerize -wait tcp://localhost:3306 -timeout 1m
    - run:
        name: Check DB connection
        command: |
          export MYSQL_HOST="127.0.0.1"
          export MYSQL_USER=circleci_test
          export MYSQL_PASSWORD=circleci_test
          export MYSQL_DB=circleci_test
          mysql -h 127.0.0.1 -P 3306 -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -e "show databases;"
  build-docker:
    docker:
    - image: cimg/go:1.20.5
    - image: cimg/mysql:8.0
    steps:
    - checkout
    - run:
        name: Docker build Command
        command: docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:latest
  build-docker-on-remote:
    docker:
    - image: cimg/go:1.20.5
    - image: cimg/mysql:8.0
    steps:
    - setup_remote_docker:
        docker_layer_caching: false
    - checkout
    - run:
        name: Docker build Command
        command: docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:latest
workflows:
  version: 2
  build-workflow:
    jobs:
    - build-dockerize
    - build-dockerize-on-remote
    - build-docker
    - build-docker-on-remote
