version: 2.1

jobs:
  build:
    docker:
      - image: node:slim
    steps:
      - checkout
      - run: echo "Hello World!"
      
  build_2:
    machine:
      image: ubuntu-2204:2023.07.2
    resource_class: large
    steps:
      - run: docker info
      
workflows:
  test_workflow:
    jobs:
      - build_2
      
