version: 2.1

jobs:
  build:
    machine: true
    resource_class: jkscci/local-mac-runner
    steps:
      - checkout
      - run: echo "Hello World!"
      
workflows:
  test_workflow:
    jobs:
      - build
      
