version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build:
    docker:
      - image: node:slim
    steps:
      - checkout
      - run: echo "Hello World!"
  cypress:
    executor:
      name: node/default
      tag: '21.4.0'
    steps:
      - run: echo "Hello executor"
      - run: node -v
      
workflows:
  test_workflow:
    jobs:
      - build
      - cypress
      
