version: 2
jobs:
  build:
    docker:
    - image: cimg/go:1.17
    - image: cimg/postgres:15.3.0
      environment:
        POSTGRES_USER: circleci-demo-go
        POSTGRES_DB: circle_test
    steps:
    - checkout
    - run:
        name: Waiting for Postgres to be ready
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
  build-docker:
    docker:
    - image: cimg/go:1.17
    - image: cimg/postgres:15.3.0
    steps:
    - checkout
    - run:
        name: Docker build Command
        command: docker build https://github.com/docker/rootfs.git#container:docker
workflows:
  version: 2
  build-workflow:
    jobs:
    - build
    - build-docker
