version: 2
jobs:
  build:
    docker:
    - image: cimg/go:1.20.5
    - image: cimg/postgres:11.20
      environment:
        POSTGRES_USER: circleci-demo-go
        POSTGRES_DB: circle_test
    steps:
    - checkout
    - run:
        name: Waiting for Postgres to be ready
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
  build-docker:
    docker:
    - image: cimg/go:1.20.5
    - image: cimg/postgres:11.20
    steps:
    - checkout
    - run:
        name: Docker build Command
        command: docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:latest
  build-docker-on-remote:
    docker:
    - image: cimg/go:1.20.5
    - image: cimg/postgres:11.20
    steps:
    - setup_remote_docker:
        docker_layer_caching: false
    - checkout
    - run:
        name: Docker build Command
        command: docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:latest
workflows:
  version: 2
  build-workflow:
    jobs:
    - build
    - build-docker
    - build-docker-on-remote
