version: 2.1

jobs:
  build:
    docker:
      - image: node:slim
    steps:
      - checkout
      - run: echo "Hello World!"
      - run: docker info
      
workflows:
  test_workflow:
    jobs:
      - build
      
