version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.12
    - image: circleci/postgres:9.6-alpine
      environment:
        POSTGRES_USER: circleci-demo-go
        POSTGRES_DB: circle_test
    parallelism: 2
    steps:
    - checkout
    - run:
        name: Waiting for Postgres to be ready
        command: dockerize -wait tcp://localhost:5432 -timeout 1m
    - run:
        name: Start service
        environment:
          CONTACTS_DB_URL: postgres://circleci-demo-go@localhost:5432/circle_test?sslmode=disable
          CONTACTS_DB_MIGRATIONS: /home/circleci/project/db/migrations
        command: ./workdir/contacts
        background: true
    - run:
        name: Validate service is working
        command: |
          sleep 5
          curl --retry 10 --retry-delay 1 -X POST --header "Content-Type: application/json" -d '{"email":"test@example.com","name":"Test User"}' http://localhost:8080/contacts
workflows:
  version: 2
  build-workflow:
    jobs:
    - build
