version: 2.1
jobs:
  build:
    docker:
      # CircleCI PostgreSQL images available at: https://circleci.com/developer/images/image/cimg/postgres
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: circleci-demo-go
          POSTGRES_DB: circle_test

    steps:
      #  Wait for Postgres to be ready before proceeding
      - run:
          name: Waiting for Postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m